#!/usr/bin/env bash

branch="development"
native_version="2025.1.1"
java_version="2025.1.1"

native_tools=(
    "DataLogTool"
    "Glass"
    "OutlineViewer"
    "SysId"
    "roboRIOTeamNumberSetter"
    "wpical"
)

java_tools=(
    "PathWeaver"
    "SmartDashboard"
    "Shuffleboard"
    "RobotBuilder"
)

for tool in "${native_tools[@]}"; do
    ./fetch_hashes.clj --tool "$tool" --branch "$branch" --version "$native_version" --type native
    echo
done

for tool in "${java_tools[@]}"; do
    ./fetch_hashes.clj --tool "$tool" --branch "$branch" --version "$java_version" --type java
    echo
done
