#!/usr/bin/env bash

branch="release"
native_version="2025.3.1"
java_version="2025.3.1"

native_tools=(
    "DataLogTool"
    "Glass"
    "OutlineViewer"
    "SysId"
    "roboRIOTeamNumberSetter"
    "wpical"
)

java_tools=(
    "PathWeaver"
    "SmartDashboard"
    "Shuffleboard"
    "RobotBuilder"
)

github_tools=(
    "Elastic"
    "Choreo"
    "AdvantageScope"
    "Pathplanner"
    "wpilibutility"
    "vscode-extension"
)

github_versions=(
    "2025.1.0"
    "2025.0.3"
    "4.1.2"
    "2025.2.2"
    "2025.3.1"
    "2025.3.1"
)

for tool in "${native_tools[@]}"; do
    bun fetch_hashes.ts --tool "$tool" --branch "$branch" --version "$native_version" --type native
    echo
done

for tool in "${java_tools[@]}"; do
    bun fetch_hashes.ts --tool "$tool" --branch "$branch" --version "$java_version" --type java
    echo
done

for i in "${!github_tools[@]}"; do
    tool="${github_tools[$i]}"
    version="${github_versions[$i]}"
    bun fetch_hashes.ts --tool "$tool" --branch "na" --version "$version" --type github
    echo
done
