#!/usr/bin/env bash

branch="release"
native_version="2025.3.1"
java_version="2025.3.1"

native_tools=(
    "DataLogTool"
    "Glass"
    "OutlineViewer"
    "SysId"
    "roboRIOTeamNumberSetter"
    "wpical"
    "wpilibutility"
    "vscode-extension"
)

java_tools=(
    "PathWeaver"
    "SmartDashboard"
    "Shuffleboard"
    "RobotBuilder"
)

for tool in "${native_tools[@]}"; do
    bun fetch_hashes.ts --tool "$tool" --branch "$branch" --version "$native_version" --type native
    echo
done

for tool in "${java_tools[@]}"; do
    bun fetch_hashes.ts --tool "$tool" --branch "$branch" --version "$java_version" --type java
    echo
done
